USE [GourmetShop]
GO

ALTER TABLE [dbo].[OrderItem] DROP CONSTRAINT [FK_ORDERITE_REFERENCE_PRODUCT]
GO

ALTER TABLE [dbo].[OrderItem]  WITH CHECK ADD  CONSTRAINT [FK_ORDERITE_REFERENCE_PRODUCT] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id]) on delete cascade
GO

ALTER TABLE [dbo].[OrderItem] CHECK CONSTRAINT [FK_ORDERITE_REFERENCE_PRODUCT]
GO


